eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://111.230.234.114:9411/
  application:
    name: product-service
server:
  port: 8771
